-- SELECT ALL THE ITEMS FROM THE ORDER_ITEMS TABLE WITH ORDER_ID 2 AND SORT BY TOTAL_PRICE IN DESCENDING ORDER
SELECT *,QUANTITY * UNIT_PRICE AS TOTAL_PRICE
FROM ORDER_ITEMS
WHERE ORDER_ID = 2 
-- ORDER BY (QUANTITY * UNIT_PRICE) DESC
ORDER BY TOTAL_PRICE DESC