-- GET THE CUSTOMER WHERE 
-- 	ADDRESSES CONTAIN TRAIL OR AVENUE

-- SELECT * FROM CUSTOMERS
-- WHERE ADDRESS LIKE '%trail%' OR ADDRESS LIKE '%AVENUE%'

--     PHONE NUMBERS END WITH 9
SELECT * FROM CUSTOMERS
WHERE PHONE LIKE '%9'