-- SELECT * FROM CUSTOMERS
-- ORDER BY STATE DESC, FIRST_NAME


-- SELECT FIRST_NAME,LAST_NAME
-- FROM CUSTOMERS
-- ORDER BY BIRTH_DATE

-- SELECT FIRST_NAME,LAST_NAME,10 AS POINTS
-- FROM CUSTOMERS 
-- ORDER BY POINTS, FIRST_NAME

-- TRY TO AVOID THIS
SELECT FIRST_NAME,LAST_NAME,10 AS POINTS
FROM CUSTOMERS 
ORDER BY 1,2

