SELECT * FROM CUSTOMERS
-- WHERE LAST_NAME REGEXP 'FIELD$'
-- WHERE LAST_NAME REGEXP '^FIELD'
-- WHERE LAST_NAME REGEXP 'FIELD$|MAC|ROSE'
-- WHERE LAST_NAME REGEXP '[GIM]E'
-- WHERE LAST_NAME REGEXP 'E[ABCD]'
WHERE LAST_NAME REGEXP '[A-H]E'